### ISSUE TITLE
Type errors with 3.10.0 in Vue template section (Nuxt project)

### ISSUE THREAD

**Issue by Anton-Plagemann** [unjs/unimport#361]
### Environment

Project info:

------------------------------
- Operating System: Linux
- **Unimport version: 3.10.0**
- Node Version:     v20.15.0
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.7.0
- Builder:          -
- User Config:      app, build, compatibilityDate, debug, devtools, future, hooks, i18n, imports, modules, nitro, routeRules, runtimeConfig, security, ssr, sourcemap, tailwindcss, postcss, telemetry, vite
- Runtime Modules:  @nuxt/eslint@0.5.0, @pinia/nuxt@0.5.3, @vueuse/nuxt@10.11.0, @nuxtjs/i18n@8.3.3, nuxt-security@2.0.0-rc.9, @nuxtjs/tailwindcss@6.12.1
- Build Modules:    -
------------------------------

### Reproduction

Let me know if you need a reproduction repo.

### Describe the bug

Starting from unimport 3.10.0 I get type errors like these all over my nuxt app (see log section for a full example output):
![image](https://github.com/user-attachments/assets/04635224-25b5-4a65-b97e-5ee55dd6cf7b)

I tracked it down to the following code change (Line 84 to 91): 
https://github.com/unjs/unimport/compare/v3.9.1...v3.10.0#diff-ff328eec8d9ee3a30a4b685a1fe08482bc3edf274cba60669ce7869375d6d5e9

Reversing it make the errors disappear (using 3.9.1 does so too). Maybe it was removed by accident?
The issue emerged, when I updated @nuxt/eslint from 0.4.0 to 0.5.0 which also updated unimport from 3.9.1 to 3.10.0.

### Logs

```sh
Property 'useRoute' does not exist on type 'CreateComponentPublicInstance<Readonly<ExtractPropTypes<{}>>, { providerLogos: typeof providerLogos; t: typeof t; providerNames: typeof providerNames; auth: typeof auth; user: typeof user; redirectUrl: typeof redirectUrl; }, ... 17 more ..., {}>'.ts-plugin(2339)
```

**Comment by byronogis** [comment]
I have encountered the same type of problem, and after a simple test, I found that it was caused by the import of a custom third-party package.

You can try disabling custom imports, regenerating type files, and troubleshooting problematic third-party package imports.

**Comment by byronogis** [comment]
Check if you can reproduce the issue with other dependencies. I encountered the same problem when using the new version of peimvue, and I found a related issue at that time.

https://github.com/primefaces/primevue/issues/6199

**Comment by Anton-Plagemann** [comment]
Seems like this is caused by a change, how libraries augment the `vue`-type. See [here](https://github.com/nuxt/nuxt/releases/tag/v3.13.0#:~:text=by%20creating%20a-,declarations.d.ts,-in%20the%20root) for the reason and a temporary fix that worked for me.
Closing this issue, as it seems there's nothing wrong with `unimport` 😊
